"""empty message

Revision ID: 830878abe1c4
Revises: 
Create Date: 2020-03-24 15:36:51.653484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '830878abe1c4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pets',
    sa.Column('animal_id', sa.Integer(), nullable=False),
    sa.Column('animal_subid', sa.String(), nullable=True),
    sa.Column('animal_area_pkid', sa.Integer(), nullable=True),
    sa.Column('animal_shelter_pkid', sa.Integer(), nullable=True),
    sa.Column('animal_place', sa.String(), nullable=True),
    sa.Column('animal_kind', sa.String(), nullable=True),
    sa.Column('animal_sex', sa.String(), nullable=True),
    sa.Column('animal_bodytype', sa.String(), nullable=True),
    sa.Column('animal_colour', sa.String(), nullable=True),
    sa.Column('animal_age', sa.String(), nullable=True),
    sa.Column('animal_sterilization', sa.String(), nullable=True),
    sa.Column('animal_bacterin', sa.String(), nullable=True),
    sa.Column('animal_foundplace', sa.String(), nullable=True),
    sa.Column('animal_title', sa.String(), nullable=True),
    sa.Column('animal_status', sa.String(), nullable=True),
    sa.Column('animal_remark', sa.String(), nullable=True),
    sa.Column('animal_caption', sa.String(), nullable=True),
    sa.Column('animal_opendate', sa.String(), nullable=True),
    sa.Column('animal_closeddate', sa.String(), nullable=True),
    sa.Column('animal_update', sa.String(), nullable=True),
    sa.Column('animal_createtime', sa.String(), nullable=True),
    sa.Column('shelter_name', sa.String(), nullable=True),
    sa.Column('album_file', sa.String(), nullable=True),
    sa.Column('album_update', sa.String(), nullable=True),
    sa.Column('cDate', sa.String(), nullable=True),
    sa.Column('shelter_address', sa.String(), nullable=True),
    sa.Column('shelter_tel', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('animal_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pets')
    # ### end Alembic commands ###
